# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  DOXYFILE: $TRAVIS_BUILD_DIR/DOXYFILE
  github_token: $GH_REPO_TOKEN
  on:
    branch: gh-pages

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh