name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
        - main
        - printip
 
jobs:
  build-documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Build the HTML documentation
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
          doxyfile-path: ./Doxyfile
          working-directory: ./IPAddressPrint
    
    # Deploy the HTML documentation to GitHub Pages
    - name: GH Pages Deployment
      uses: DenverCoder1/doxygen-github-pages-action@v1.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        config_file: Doxyfile
        publish_branch: gh-pages