name: 'C++ CI'

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake libgtest-dev -y 
          pip uninstall conan -y
          pip install -U conan==1.62.0
      - name: Install conan
        run: |
          cd ./BuildTestDeploy
          mkdir build && cd build
          conan install .. --build=missing -s build_type=Release
      - name: Cmake
        run: |
          cd ./bulk/build 
          cmake .. -DPATCH_VERSION=${{ github.run_number }}
      - name: Build
        run: |
          cd ./bulk/build 
          cmake --build .
      - name: Build Test
        run: |
          cd ./bulk/build 
          cmake --build . --target utest
      - name: Build package
        run: |
          cd ./bulk/build 
          cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: bulk-${{ github.run_number }}
          release_name: Release bulk ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .//bulk/build/packages/bulk-0.0.${{ github.run_number }}-Linux.deb
          asset_name: bulk-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
